name: Docker Build

on:
  push:
    branches: ["main"]

  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (optional)"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        id: tag
        run: |
          IMAGE=ghcr.io/andeasw/sbkojs

          if [ -n "${{ github.event.inputs.version }}" ]; then
            TAG=${{ github.event.inputs.version }}
          else
            TAG=latest
          fi

          echo "tag=$IMAGE:$TAG" >> $GITHUB_OUTPUT

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.tag.outputs.tag }}
